twig:
    default_path: '%kernel.project_dir%/templates'
    path: '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
